In [1]:
#Standard imports:
import numpy as np
import pandas as pd
import matplotlib as plt
%matplotlib inline

# 3. Fit the model to the data and use it make predictions:

## 3.1 Fitting the model to the data:

In [4]:
heart_disease = pd.read_csv("heart-disease.csv")
#import linear Svc
from sklearn.ensemble import RandomForestClassifier

#Setting up randomn seed:
np.random.seed(42)

#creating the data:
x= heart_disease.drop("target", axis =1)
y= heart_disease["target"]

#Spliting the data into training and test sets:
from sklearn.model_selection import train_test_split
x_train,x_test , y_train,y_test = train_test_split(x,y, test_size= 0.2)

#Instiniate the Linear model
clf = RandomForestClassifier()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)



0.8524590163934426

## 3.2 Make prediction using  machine learning tool

2 ways two make predictions:

1. predit()
2. predict_proba()

In [5]:
#Use a train model to make predictoions
clf.predict(np.array([1,2,3,4,5]))

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3. 4. 5.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [6]:
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [7]:
np.array([y_test])

array([[0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0]])

In [8]:
# comparing the prediction with truth labels to evaluate the model
y_preds = clf.predict(x_test)
np.mean (y_test == y_preds)

0.8524590163934426

### 2. Predict_proba()
Predict proba returns probabilities of a classification value

In [10]:
clf.predict_proba(x_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [13]:
x_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [14]:
# CAn use predict for regression model also
#import Boston housing data
from sklearn.datasets import load_boston
boston = load_boston();
boston;

boston_df = pd.DataFrame(boston["data"], columns = boston["feature_names"])
boston_df["target"]= pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [17]:
#Lets try RandomForest:
from sklearn.ensemble import RandomForestRegressor

#Setting up Random Seed
np.random.seed(42)

#Creating the data
x = boston_df.drop("target", axis =1)
y = boston_df["target"]

#Spliting the data into training and test sets:
x_train,x_test , y_train,y_test = train_test_split(x,y, test_size= 0.2)

#Instantiate RandomForrest Model
model = RandomForestRegressor()
model.fit(x_train,y_train)

#Make prediction
y_preds = model.predict(x_test)



0.0

In [21]:
y_preds[:10]

array([23.081, 30.574, 16.759, 23.46 , 16.893, 21.644, 19.113, 15.334,
       21.14 , 20.639])

In [23]:
np.array(y_test[:10])

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8])

In [24]:
# Compare the prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error (y_test,y_preds)

2.136382352941176